title: Aalok Yadav
author: Aalok Yadav
email: 
description: Everything I know is here

github_username: aalokyadav96
# twitter_username:
# facebook_username:
# dribbble_username:

# date_format:

# google_analytics:
# disqus_shortname:
blog_theme: auto

markdown: kramdown

plugins:
 - jekyll-feed
 - jekyll-seo-tag
