# Site settings
title: "Aalok Yadav"
description: > 
  Everything I know is here.

author: Aalok Yadav
email: 
twitter_username: 
github_username: aalokyadav96

baseurl: "/" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site

#google_analytics_id: 
#disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

